### ISSUE TITLE
"Shall" is not accounted for in negations

### ISSUE THREAD

**Issue by ibrahimgh26** [dmlls/negate#12]
"Shall" should be added to the rules. As the systems correctly accounts for should, must, and other model verbs. I think this is an easy fix.

Current behavior:
Negating "The system shall be ok." returns "The system shall don't be ok."
Expected behavior:
The negator should return: "The system shall not be ok."
Used code:

```
from negate import Negator

negator = Negator()

sentence = "The system shall be ok."
negated_sentence = negator.negate_sentence(sentence)

print(negated_sentence)
```

Python 3.10.12
The issue was recreated on negate 1.1.3 (installed from pypi), and the package built from source (pip install git+https://github.com/dmlls/negate)

**Comment by dmlls** [comment]
Hey @ibrahimgh26, thanks for the catch and the detailed report! Unsure how this went unnoticed until now...

Anyways, the fix is ready and published here and at https://pypi.org/project/negate/. It was, as you said, a rather easy fix. Unfortunately the [`en_core_web_md`](https://spacy.io/models/en#en_core_web_md) model tends to misclassify the (admittedly rare) "shan't", so I had to add a couple of workarounds. Hopefully models are improved soon and then... they shall be removed 😉

**Comment by ibrahimgh26** [comment]
Hello,

thanks for the quick response, and the quick fix.
